### ISSUE TITLE
problem getting it to work

### ISSUE THREAD

**Issue by fkgruber** [ParetoOptimalDev/org-inline-clocking-buttons#1]
I downloaded the el file and used:
(require 'svg-lib)
(load-file "~/elisp/org-inline-clocking-buttons.el")

but when I activate it I get a tiny little icon which activates the clock but won't let me deactivate.
![image](https://user-images.githubusercontent.com/4311763/228346944-4452ee83-a4aa-4846-810f-ce41dd2fa5d4.png)

**Comment by ParetoOptimalDev** [comment]
Sorry about that!

I'll try to look at it again as soon as I find some spare time.

Until then you might want to try the version before I switched to svg icons and refactored at 1d042359da07eb9dbd5d0a7366bdcbc6f5712e06

**Comment by fkgruber** [comment]
thanks. THis version works.

By the way it would seem to make sense to remove the button once the task becomes DONE?

**Comment by ParetoOptimalDev** [comment]
Will address this in #2, closing this one though.
